// Hämtar matchdata från CupManager-API:et och sparar till jsons/data.js.
//   node generate-data.js
//
// Cupar och matcher konfigureras i matches.js.

const https  = require('https');
const fs     = require('fs');
const path   = require('path');
const agent  = new https.Agent({ rejectUnauthorized: false });

// Läs in MATCH_CONFIG från matches.js
const matchesJs = fs.readFileSync(path.join(__dirname, 'matches.js'), 'utf8');
let MATCH_CONFIG;
try {
  const win = {};
  new Function('window', matchesJs)(win);
  MATCH_CONFIG = win.MATCH_CONFIG;
} catch (e) {
  console.error('Kunde inte läsa matches.js:', e.message);
  process.exit(1);
}

const cups = MATCH_CONFIG?.cups;
if (!cups?.length) {
  console.error('MATCH_CONFIG.cups saknas eller är tomt i matches.js');
  process.exit(1);
}

function extractMatchName(data) {
  let home = '', away = '';
  for (const [key, val] of Object.entries(data.responses || {})) {
    if (val.entity?.__typename !== 'MatchActor') continue;
    const name = val.entity.name?.sv || val.entity.name?.en || '';
    if (!name) continue;
    if (key.includes('"home"')) home = name;
    if (key.includes('"away"')) away = name;
  }
  return home && away ? `${home} – ${away}` : null;
}

function buildQuery(id) {
  return `Match({id:${id}}){home:{team:{club:{nation:{}},statistics:{}}},away:{team:{club:{nation:{}},statistics:{}}},feed:{statistics:{},events:[{}]},result:{}}`;
}

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { agent }, res => {
      let raw = '';
      res.on('data', c => raw += c);
      res.on('end', () => {
        try { resolve(JSON.parse(raw)); }
        catch (e) { reject(new Error('Parse-fel: ' + e.message)); }
      });
    }).on('error', reject);
  });
}

async function fetchTeamMatchIds(teamId, baseUrl, tournamentId) {
  const q    = encodeURIComponent(`Team({id:${teamId}}){matches:[{home:{},away:{},result:{}}]}`);
  const url  = `${baseUrl}?call=${q}&lang=en&tournamentId=${tournamentId}`;
  const data = await fetchJson(url);
  const ids  = new Set();
  let teamName = `Team ${teamId}`;
  for (const [key, val] of Object.entries(data.responses || {})) {
    const m = key.match(/^Match\(\{id:(\d+)\}\)$/);
    if (m) ids.add(parseInt(m[1]));
    if (key === `Team({id:${teamId}})` && val.entity?.__typename === 'Team') {
      teamName = val.entity.name?.clubName || val.entity.name?.fullName || teamName;
    }
  }
  return { ids: [...ids], teamName };
}

async function main() {
  const games = [];

  for (const cup of cups) {
    const { name: cupName, baseUrl, tournamentId, matches = [], teamIds = [] } = cup;
    console.log(`\n[${cupName}]`);

    // matchId -> { teamId, teamName }
    const matchTeamMap = {};
    const manualNames  = Object.fromEntries(matches.filter(m => m.name).map(m => [m.id, m.name]));
    const allIds       = matches.map(m => m.id);

    for (const teamId of teamIds) {
      process.stdout.write(`  Hämtar matcher för lag ${teamId}... `);
      try {
        const { ids, teamName } = await fetchTeamMatchIds(teamId, baseUrl, tournamentId);
        let added = 0;
        for (const id of ids) {
          if (!matchTeamMap[id]) matchTeamMap[id] = { teamId, teamName };
          if (!allIds.includes(id)) { allIds.push(id); added++; }
        }
        console.log(`✓  ${teamName} (${ids.length} matcher, ${added} nya)`);
      } catch (e) {
        console.log(`✗  ${e.message}`);
      }
    }

    for (const id of allIds) {
      const teamInfo   = matchTeamMap[id] || null;
      const manualName = manualNames[id];
      process.stdout.write(`  Match ${id}... `);
      try {
        const q    = encodeURIComponent(buildQuery(id));
        const url  = `${baseUrl}?call=${q}&lang=en&tournamentId=${tournamentId}`;
        const data = await fetchJson(url);
        const name = manualName || extractMatchName(data) || `Match ${id}`;
        games.push({ name, cup: cupName, teamId: teamInfo?.teamId || null, teamName: teamInfo?.teamName || null, data });
        console.log(`✓  ${name}`);
      } catch (e) {
        console.log('✗  ' + e.message);
      }
    }
  }

  if (!games.length) {
    console.error('\nInga matcher hämtades.');
    process.exit(1);
  }

  const outDir = path.join(__dirname, 'jsons');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir);
  const output = `// Auto-generated by generate-data.js — do not edit manually\nwindow.GAME_DATA = ${JSON.stringify(games)};\n`;
  fs.writeFileSync(path.join(outDir, 'data.js'), output, 'utf8');
  console.log(`\nKlart! ${games.length} match(er) sparade till jsons/data.js`);
}

main().catch(e => { console.error(e); process.exit(1); });
