// Hämtar matchdata från CupManager-API:et och sparar till jsons/data.js.
//   node generate-data.js
//
// Cupar och matcher konfigureras i matches.js.

const https  = require('https');
const fs     = require('fs');
const path   = require('path');
const agent  = new https.Agent({ rejectUnauthorized: false });

// Läs in MATCH_CONFIG från matches.js
const matchesJs = fs.readFileSync(path.join(__dirname, 'matches.js'), 'utf8');
let MATCH_CONFIG;
try {
  const win = {};
  new Function('window', matchesJs)(win);
  MATCH_CONFIG = win.MATCH_CONFIG;
} catch (e) {
  console.error('Kunde inte läsa matches.js:', e.message);
  process.exit(1);
}

const cups = MATCH_CONFIG?.cups;
if (!cups?.length) {
  console.error('MATCH_CONFIG.cups saknas eller är tomt i matches.js');
  process.exit(1);
}

function extractMatchName(data) {
  let home = '', away = '';
  for (const [key, val] of Object.entries(data.responses || {})) {
    if (val.entity?.__typename !== 'MatchActor') continue;
    const name = val.entity.name?.sv || val.entity.name?.en || '';
    if (!name) continue;
    if (key.includes('"home"')) home = name;
    if (key.includes('"away"')) away = name;
  }
  return home && away ? `${home} – ${away}` : null;
}

function buildQuery(id) {
  return `Match({id:${id}}){home:{},away:{},feed:{events:[{}]},result:{}}`;
}

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { agent }, res => {
      let raw = '';
      res.on('data', c => raw += c);
      res.on('end', () => {
        try { resolve(JSON.parse(raw)); }
        catch (e) { reject(new Error('Parse-fel: ' + e.message)); }
      });
    }).on('error', reject);
  });
}

async function main() {
  const games = [];

  for (const cup of cups) {
    const { name: cupName, baseUrl, tournamentId, matches = [] } = cup;
    console.log(`\n[${cupName}]`);
    for (const m of matches) {
      process.stdout.write(`  Match ${m.id}... `);
      try {
        const q    = encodeURIComponent(buildQuery(m.id));
        const url  = `${baseUrl}?call=${q}&lang=en&tournamentId=${tournamentId}`;
        const data = await fetchJson(url);
        const name = m.name || extractMatchName(data) || `Match ${m.id}`;
        games.push({ name, cup: cupName, data });
        console.log(`✓  ${name}`);
      } catch (e) {
        console.log('✗  ' + e.message);
      }
    }
  }

  if (!games.length) {
    console.error('\nInga matcher hämtades.');
    process.exit(1);
  }

  const outDir = path.join(__dirname, 'jsons');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir);
  const output = `// Auto-generated by generate-data.js — do not edit manually\nwindow.GAME_DATA = ${JSON.stringify(games)};\n`;
  fs.writeFileSync(path.join(outDir, 'data.js'), output, 'utf8');
  console.log(`\nKlart! ${games.length} match(er) sparade till jsons/data.js`);
}

main().catch(e => { console.error(e); process.exit(1); });
